<a href="https://colab.research.google.com/github/mk7890/Python_Data_Analysis/blob/main/Pandas_exercise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# Filtering and Sorting

# chipotle

In [3]:
# chipotle
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep = '\t')
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [5]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.7+ KB

In [6]:
chipo.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

In [7]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [8]:
# How many products cost more than $10.00?
# clean the item_price column and transform it in a float

filtered_df = chipo[chipo['item_price'] > 10.00]

# Count the number of rows
num_products = len(filtered_df)

print(f"Number of products that cost more than $10.00: {num_products}")

Number of products that cost more than $10.00: 1130

In [9]:
# What is the price of each item?


# Select only the 'item_name' and 'item_price' columns
price_df = chipo[['item_name', 'item_price']]

# Print the resulting DataFrame
print(price_df)

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

In [10]:
# Sort by the name of the item


# Select only the 'item_name' and 'item_price' columns
price_df = chipo[['item_name', 'item_price']]

# Sort the DataFrame by the 'item_name' column
sorted_price_df = price_df.sort_values(by='item_name')

# Print the resulting sorted DataFrame
print(sorted_price_df)

              item_name  item_price
3389  6 Pack Soft Drink       12.98
341   6 Pack Soft Drink        6.49
1849  6 Pack Soft Drink        6.49
1860  6 Pack Soft Drink        6.49
2713  6 Pack Soft Drink        6.49
...                 ...         ...
2384  Veggie Soft Tacos        8.75
781   Veggie Soft Tacos        8.75
2851  Veggie Soft Tacos        8.49
1699  Veggie Soft Tacos       11.25
1395  Veggie Soft Tacos        8.49

[4622 rows x 2 columns]

In [11]:
# What was the quantity of the most expensive item ordered?


most_expensive_item = chipo.loc[chipo['item_price'].idxmax()]

# Extract the quantity of that item
quantity_of_most_expensive_item = most_expensive_item['quantity']

print(f"Quantity of the most expensive item ordered: {quantity_of_most_expensive_item}")

Quantity of the most expensive item ordered: 15

In [12]:
# How many times was a Veggie Salad Bowl ordered?

# Filter the rows where 'item_name' is "Veggie Salad Bowl"
veggie_salad_orders = chipo[chipo['item_name'] == 'Veggie Salad Bowl']

# Count the number of orders (rows)
num_veggie_salad_orders = len(veggie_salad_orders)

print(f"Veggie Salad Bowl was ordered {num_veggie_salad_orders} times.")

Veggie Salad Bowl was ordered 18 times.

# 3. Grouping

- Alcohol Consmption

In [15]:
alcohol_url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv'
drinks = pd.read_csv(alcohol_url)
drinks

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
...,...,...,...,...,...,...
188,Venezuela,333,100,3,7.7,SA
189,Vietnam,111,2,1,2.0,AS
190,Yemen,6,0,0,0.1,AS
191,Zambia,32,19,4,2.5,AF
192,Zimbabwe,64,18,4,4.7,AF

In [16]:
drinks.columns

Index(['country', 'beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent'],
      dtype='object')

In [17]:
# Which continent drinks more beer on average?

# Group the data by continent and calculate the average beer servings
average_beer_servings = drinks.groupby('continent')['beer_servings'].mean()

# Find the continent with the highest average beer servings
continent_with_most_beer = average_beer_servings.idxmax()
highest_average_beer = average_beer_servings.max()

print(f"The continent that drinks the most beer on average is {continent_with_most_beer} with an average of {highest_average_beer} beer servings.")

The continent that drinks the most beer on average is EU with an average of 193.77777777777777 beer servings.

In [18]:
# For each continent print the statistics for wine consumption.

# Group by continent and get statistics for wine_servings
wine_statistics = drinks.groupby('continent')['wine_servings'].describe()

# Print the statistics for each continent
print(wine_statistics)

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

In [20]:
# Print the mean alcohol consumption per continent for every column


# Group by continent and calculate the mean for every relevant column
mean_alcohol_consumption = drinks.groupby('continent')[['beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol']].mean()

# Print the mean consumption per continent for each column
print(mean_alcohol_consumption)

           beer_servings  spirit_servings  wine_servings  \
continent
AF             61.471698        16.339623      16.264151
AS             37.045455        60.840909       9.068182
EU            193.777778       132.555556     142.222222
OC             89.687500        58.437500      35.625000
SA            175.083333       114.750000      62.416667

           total_litres_of_pure_alcohol
continent
AF                             3.007547
AS                             2.170455
EU                             8.617778
OC                             3.381250
SA                             6.308333

In [21]:
# Print the median alcohol consumption per continent for every column

# Group by continent and calculate the median for every relevant column
median_alcohol_consumption = drinks.groupby('continent')[['beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol']].median()

# Print the median consumption per continent for each column
print(median_alcohol_consumption)

           beer_servings  spirit_servings  wine_servings  \
continent
AF                  32.0              3.0            2.0
AS                  17.5             16.0            1.0
EU                 219.0            122.0          128.0
OC                  52.5             37.0            8.5
SA                 162.5            108.5           12.0

           total_litres_of_pure_alcohol
continent
AF                                 2.30
AS                                 1.20
EU                                10.00
OC                                 1.75
SA                                 6.85

In [22]:
# Print the mean, min and max values for spirit consumption. This time output a DataFrame


# Group by continent and calculate the mean, min, and max for spirit_servings
spirit_consumption_stats = drinks.groupby('continent')['spirit_servings'].agg(['mean', 'min', 'max'])

# Print the resulting DataFrame
print(spirit_consumption_stats)

                 mean  min  max
continent
AF          16.339623    0  152
AS          60.840909    0  326
EU         132.555556    0  373
OC          58.437500    0  254
SA         114.750000   25  302