<a href="https://colab.research.google.com/github/mk7890/Python_Data_Analysis/blob/main/Pandas_exercise4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **01 Getting and knowing your data**

# Occupation

In [1]:
import numpy as np
import pandas as pd

In [3]:
# Assign it to a variable called users and use the 'user_id' as index
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user'
users = pd.read_csv(url, sep='|', index_col='user_id')
users

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

In [4]:
# See the first 25 entries
users.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

In [5]:
# See the last 10 entries
users.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

In [7]:
# What is the number of observations in the dataset?
print(f"number of observations : {users.shape[0]}")

number of observations : 943

In [8]:
# What is the number of columns in the dataset?
print(f"number of columns : {users.shape[1]}")

number of columns : 4

In [9]:
# Print the name of all the columns.
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [10]:
# How is the dataset indexed?
users.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

In [11]:
# What is the data type of each column?
users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [12]:
# Print only the occupation column
users['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

In [13]:
# How many different occupations are in this dataset?
users['occupation'].nunique()

21

In [14]:
# What is the most frequent occupation?
users['occupation'].value_counts().idxmax()

'student'

In [15]:
# Summarize the DataFrame.
users.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

In [16]:
# Summarize all the columns
users.describe(include='all')

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

In [18]:
# Summarize only the occupation column
users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [19]:
# What is the mean age of users?
users['age'].mean()

34.05196182396607

In [20]:
# What is the age with least occurrence?
users['age'].value_counts().idxmin()

7

# **06 Stats**

## US Baby Names

In [21]:
import numpy as np
import pandas as pd

In [22]:
# importing dataset
# Assign it to a variable called baby_names.

url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv'
baby_names = pd.read_csv(url)
baby_names

         Unnamed: 0       Id     Name  Year Gender State  Count
0             11349    11350     Emma  2004      F    AK     62
1             11350    11351  Madison  2004      F    AK     48
2             11351    11352   Hannah  2004      F    AK     46
3             11352    11353    Grace  2004      F    AK     44
4             11353    11354    Emily  2004      F    AK     41
...             ...      ...      ...   ...    ...   ...    ...
1016390     5647421  5647422     Seth  2014      M    WY      5
1016391     5647422  5647423  Spencer  2014      M    WY      5
1016392     5647423  5647424     Tyce  2014      M    WY      5
1016393     5647424  5647425   Victor  2014      M    WY      5
1016394     5647425  5647426   Waylon  2014      M    WY      5

[1016395 rows x 7 columns]

In [23]:
# See the first 10 entries
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

In [24]:
# Delete the column 'Unnamed: 0' and 'Id'
baby_names.drop(['Unnamed: 0', 'Id'], axis=1, inplace=True)
baby_names

            Name  Year Gender State  Count
0           Emma  2004      F    AK     62
1        Madison  2004      F    AK     48
2         Hannah  2004      F    AK     46
3          Grace  2004      F    AK     44
4          Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
1016390     Seth  2014      M    WY      5
1016391  Spencer  2014      M    WY      5
1016392     Tyce  2014      M    WY      5
1016393   Victor  2014      M    WY      5
1016394   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

In [25]:
# Is there more male or female names in the dataset?
baby_names['Gender'].value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

In [27]:
# Group the dataset by name and assign to names
names = baby_names.groupby('Name')
names

In [31]:
# How many different names exist in the dataset?
names.nunique()

         Year  Gender  State  Count
Name
Aaban       2       1      1      1
Aadan       3       1      2      3
Aadarsh     1       1      1      1
Aaden       9       1     45     43
Aadhav      1       1      1      1
...       ...     ...    ...    ...
Zyra        5       1      3      4
Zyrah       2       1      2      2
Zyren       1       1      1      1
Zyria       7       1      3      3
Zyriah      8       1      3      5

[17632 rows x 4 columns]

In [33]:
baby_names['Name'].nunique()

17632

In [34]:
# What is the name with most occurrences?
names['Name'].value_counts().idxmax()

'Riley'

In [36]:
# How many different names have the least occurrences?

# Count the occurrences of each name
name_counts = baby_names['Name'].value_counts()

# Find the minimum count
min_count = name_counts.min()

# Find how many names have this minimum count
num_least_occurrences = (name_counts == min_count).sum()
print("Number of names with the least occurrences:", num_least_occurrences)

Number of names with the least occurrences: 3682

In [37]:
# What is the median name occurrence?
names['Name'].value_counts().median()

8.0

In [38]:
# Count the occurrences of each name
name_counts = baby_names['Name'].value_counts()

# Calculate the median occurrence
median_occurrence = name_counts.median()

# Print the result
print("Median name occurrence:", median_occurrence)

Median name occurrence: 8.0

In [39]:
# What is the standard deviation of names?
names['Name'].value_counts().std()

122.02996350814125

In [42]:
# Get a summary with the mean, min, max, std and quartiles.

# Count the occurrences of each name
name_counts = baby_names['Name'].value_counts()

# Get the summary statistics
summary_stats = name_counts.describe()

# Print the result
print(summary_stats)

count    17632.000000
mean        57.644907
std        122.029964
min          1.000000
25%          2.000000
50%          8.000000
75%         39.000000
max       1112.000000
Name: count, dtype: float64