In [ ]:
import numpy as np
import pandas as pd

# 02_Filtering_&_Sorting

# 02_Filtering_&_Sorting/Chipotle

In [ ]:
# chipotle
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep = '\t')
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [ ]:
chipo.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [ ]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [ ]:
# How many products cost more than $10.00?

# clean the item_price column and transform it in a float
chipo['item_price'] = chipo['item_price'].replace('[\$,]', '', regex=True).astype(float)  # Convert prices to float
products_above_10 = chipo[chipo['item_price'] > 10]['item_name'].nunique()

print(f"Number of products costing more than $10.00: {products_above_10}")

Number of products costing more than $10.00: 31

In [ ]:
# What is the price of each item?

# Select only the 'item_name' and 'item_price' columns
price_df = chipo[['item_name', 'item_price']]

# Print the resulting DataFrame
print(price_df)

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

In [ ]:
# Sort by the name of the item


# Select only the 'item_name' and 'item_price' columns
price_df = chipo[['item_name', 'item_price']]

# Sort the DataFrame by the 'item_name' column
sorted_price_df = price_df.sort_values(by='item_name')

# Print the resulting sorted DataFrame
print(sorted_price_df)

              item_name  item_price
3389  6 Pack Soft Drink       12.98
341   6 Pack Soft Drink        6.49
1849  6 Pack Soft Drink        6.49
1860  6 Pack Soft Drink        6.49
2713  6 Pack Soft Drink        6.49
...                 ...         ...
2384  Veggie Soft Tacos        8.75
781   Veggie Soft Tacos        8.75
2851  Veggie Soft Tacos        8.49
1699  Veggie Soft Tacos       11.25
1395  Veggie Soft Tacos        8.49

[4622 rows x 2 columns]

In [ ]:
# What was the quantity of the most expensive item ordered?


most_expensive_item = chipo.loc[chipo['item_price'].idxmax()]

# Extract the quantity of that item
quantity_of_most_expensive_item = most_expensive_item['quantity']

print(f"Quantity of the most expensive item ordered: {quantity_of_most_expensive_item}")

Quantity of the most expensive item ordered: 15

In [ ]:
# How many times was a Veggie Salad Bowl ordered?

# Filter the rows where 'item_name' is "Veggie Salad Bowl"
veggie_salad_orders = chipo[chipo['item_name'] == 'Veggie Salad Bowl']

# Count the number of orders (rows)
num_veggie_salad_orders = len(veggie_salad_orders)

print(f"Veggie Salad Bowl was ordered {num_veggie_salad_orders} times.")

Veggie Salad Bowl was ordered 18 times.

In [ ]:
# How many times did someone order more than one Canned Soda?
# Filter orders with 'Canned Soda' and quantity greater than 1
canned_soda_orders = chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)]

# Count the number of such orders
num_orders = canned_soda_orders['order_id'].nunique()

print(f"Number of times someone ordered more than one Canned Soda: {num_orders}")

Number of times someone ordered more than one Canned Soda: 18

# 02_Filtering_&_Sorting/Euro12

In [ ]:
# Step 1. Import the necessary libraries
import numpy as np
import pandas as pd

In [ ]:
# Step 2. Import the dataset from address
# Step 3. Assign it to a variable called euro12.
url='https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv'
euro12 = pd.read_csv(url)
euro12

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [ ]:
# Step 4. Select only the Goal column.
euro12['Goals']

0      4
1      4
2      4
3      5
4      3
5     10
6      5
7      6
8      2
9      2
10     6
11     1
12     5
13    12
14     5
15     2
Name: Goals, dtype: int64

In [ ]:
# Step 5. How many teams participated in the Euro2012?
print(f"Number of teams that participated in Euro2012 : {euro12['Team'].nunique()}")

Number of teams that participated in Euro2012 : 16

In [ ]:
# Step 6. What is the number of columns in the dataset?
print(f"Number of columns in the dataset : {euro12.shape[1]}")

Number of columns in the dataset : 35

In [ ]:
# Step 7. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline
discipline = euro12[['Team', 'Yellow Cards', 'Red Cards']]
discipline

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

In [ ]:
# Step 8. Sort the teams by Red Cards, then to Yellow Cards
discipline.sort_values(by=['Red Cards', 'Yellow Cards'], ascending=False)

                   Team  Yellow Cards  Red Cards
6                Greece             9          1
9                Poland             7          1
11  Republic of Ireland             6          1
7                 Italy            16          0
10             Portugal            12          0
13                Spain            11          0
0               Croatia             9          0
1        Czech Republic             7          0
14               Sweden             7          0
4                France             6          0
12               Russia             6          0
3               England             5          0
8           Netherlands             5          0
15              Ukraine             5          0
2               Denmark             4          0
5               Germany             4          0

In [ ]:
# Step 9. Calculate the mean Yellow Cards given per Team
mean_yellow_cards = discipline['Yellow Cards'].mean()
print(f"Mean Yellow Cards given per Team : {mean_yellow_cards}")

Mean Yellow Cards given per Team : 7.4375

In [ ]:
# Step 10. Filter teams that scored more than 6 goals
euro12[euro12['Goals'] > 6]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18

In [ ]:
# Step 11. Select the teams that start with G

# Filter teams that start with the letter 'G'
filtered_teams = euro12[euro12['Team'].str.startswith('G')]

# Display the filtered DataFrame
filtered_teams

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20

In [ ]:
# Step 12. Select the first 7 columns
euro12.iloc[:, :7]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked)
0,Croatia,4,13,12,51.9%,16.0%,32
1,Czech Republic,4,13,18,41.9%,12.9%,39
2,Denmark,4,10,10,50.0%,20.0%,27
3,England,5,11,18,50.0%,17.2%,40
4,France,3,22,24,37.9%,6.5%,65
5,Germany,10,32,32,47.8%,15.6%,80
6,Greece,5,8,18,30.7%,19.2%,32
7,Italy,6,34,45,43.0%,7.5%,110
8,Netherlands,2,12,36,25.0%,4.1%,60
9,Poland,2,15,23,39.4%,5.2%,48
10,Portugal,6,22,42,34.3%,9.3%,82
11,Republic of Ireland,1,7,12,36.8%,5.2%,28
12,Russia,5,9,31,22.5%,12.5%,59
13,Spain,12,42,33,55.9%,16.0%,100
14,Sweden,5,17,19,47.2%,13.8%,39
15,Ukraine,2,7,26,21.2%,6.0%,38

In [ ]:
# Step 13. Select all columns except the last 3
euro12.iloc[:, :-3]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,0,10,3,13,81.3%,41,62,2,9,0
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,1,10,6,9,60.1%,53,73,8,7,0
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,1,10,5,10,66.7%,25,38,8,4,0
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,2,29,3,22,88.1%,43,45,6,5,0
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,1,7,5,6,54.6%,36,51,5,6,0
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,1,11,6,10,62.6%,63,49,12,4,0
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,1,23,7,13,65.1%,67,48,12,9,1
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,2,18,7,20,74.1%,101,89,16,16,0
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,0,9,5,12,70.6%,35,30,3,5,0
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,0,8,3,6,66.7%,48,56,3,7,1
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,2,11,4,10,71.5%,73,90,10,12,0
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,0,23,9,17,65.4%,43,51,11,6,1
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,0,8,3,10,77.0%,34,43,4,6,0
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,5,8,1,15,93.8%,102,83,19,11,0
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,1,12,5,8,61.6%,35,51,7,7,0
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,0,4,4,13,76.5%,48,31,4,5,0

In [ ]:
# Step 14. Present only the Shooting Accuracy from England, Italy and Russia

# Filter the data for teams from England, Italy, and Russia
filtered_countries = ['England', 'Italy', 'Russia']
filtered_data = euro12[euro12['Team'].isin(filtered_countries)]

# Select only the relevant columns: 'Team' and 'Shooting Accuracy'
shooting_accuracy = filtered_data[['Team', 'Shooting Accuracy']]

# Display the results
shooting_accuracy

       Team Shooting Accuracy
3   England             50.0%
7     Italy             43.0%
12   Russia             22.5%

# 02_Filtering_&_Sorting/Fictional Army

In [ ]:
# Step 1. Import the necessary libraries
import numpy as np
import pandas as pd

In [ ]:
# Create an example dataframe about a fictional army
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']}

In [ ]:
# Step 3. Create a dataframe and assign it to a variable called army.
# Don't forget to include the columns names in the order presented in the dictionary
# ('regiment', 'company', 'deaths'...) so that the column index order is consistent with the solutions.
# If omitted, pandas will order the columns alphabetically.
army = pd.DataFrame(raw_data)
army

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
4,Dragoons,1st,43,4,1592,73,2,0,3,Maine
5,Dragoons,1st,234,7,1006,37,1,1,4,Iowa
6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
7,Dragoons,2nd,62,3,849,48,3,1,31,Washington
8,Scouts,1st,62,4,973,48,2,0,2,Oregon
9,Scouts,1st,73,7,1005,435,1,0,3,Wyoming
10,Scouts,2nd,37,8,1099,63,2,1,2,Louisana
11,Scouts,2nd,35,9,1523,345,3,1,3,Georgia

In [ ]:
# Step 4. Set the 'origin' colum as the index of the dataframe
army.set_index('origin', inplace=True)
army

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

In [ ]:
# Step 5. Print only the column veterans
army['veterans']

origin
Arizona         1
California      5
Texas          62
Florida        26
Maine          73
Iowa           37
Alaska        949
Washington     48
Oregon         48
Wyoming       435
Louisana       63
Georgia       345
Name: veterans, dtype: int64

In [ ]:
# Step 6. Print the columns 'veterans' and 'deaths'
army[['veterans', 'deaths']]

            veterans  deaths
origin
Arizona            1     523
California         5      52
Texas             62      25
Florida           26     616
Maine             73      43
Iowa              37     234
Alaska           949     523
Washington        48      62
Oregon            48      62
Wyoming          435      73
Louisana          63      37
Georgia          345      35

In [ ]:
# Step 7. Print the name of all the columns.
print(army.columns)

Index(['regiment', 'company', 'deaths', 'battles', 'size', 'veterans',
       'readiness', 'armored', 'deserters'],
      dtype='object')

In [ ]:
# Step 8. Select the 'deaths', 'size' and 'deserters' columns from Maine and Alaska
army.loc[['Maine', 'Alaska'], ['deaths', 'size', 'deserters']]

        deaths  size  deserters
origin
Maine       43  1592          3
Alaska     523   987         24

In [ ]:
# Step 9. Select the rows 3 to 7 and the columns 3 to 6
army.iloc[2:7, 2:6]

         deaths  battles  size  veterans
origin
Texas        25        2  1099        62
Florida     616        2  1400        26
Maine        43        4  1592        73
Iowa        234        7  1006        37
Alaska      523        8   987       949

In [ ]:
# Step 10. Select every row after the fourth row and all columns
army.iloc[4:, :]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

In [ ]:
# Step 11. Select every row up to the 4th row and all columns
army.iloc[:4, :]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2

In [ ]:
# Step 12. Select the 3rd column up to the 7th column
army.iloc[:, 2:7]

            deaths  battles  size  veterans  readiness
origin
Arizona        523        5  1045         1          1
California      52       42   957         5          2
Texas           25        2  1099        62          3
Florida        616        2  1400        26          3
Maine           43        4  1592        73          2
Iowa           234        7  1006        37          1
Alaska         523        8   987       949          2
Washington      62        3   849        48          3
Oregon          62        4   973        48          2
Wyoming         73        7  1005       435          1
Louisana        37        8  1099        63          2
Georgia         35        9  1523       345          3

In [ ]:
# Step 13. Select rows where deaths is greater than 50
deaths_greater_than_50 = army[army['deaths'] > 50]
deaths_greater_than_50

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3

In [ ]:
# Step 15. Select all the regiments not named "Dragoons"
regiment_not_Dragoons = army[army['regiment'] != 'Dragoons']
regiment_not_Dragoons

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

In [ ]:
# Step 16. Select the rows called Texas and Arizona
army.loc[['Texas', 'Arizona']]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4

In [ ]:
# Step 17. Select the third cell in the row named Arizona
army.loc['Arizona', army.columns[2]]

523

In [ ]:
# Step 18. Select the third cell down in the column named deaths
army.iloc[2, army.columns.get_loc('deaths')]

25

# 3. Grouping

- Alcohol Consmption

In [ ]:
alcohol_url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv'
drinks = pd.read_csv(alcohol_url)
drinks

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
...,...,...,...,...,...,...
188,Venezuela,333,100,3,7.7,SA
189,Vietnam,111,2,1,2.0,AS
190,Yemen,6,0,0,0.1,AS
191,Zambia,32,19,4,2.5,AF
192,Zimbabwe,64,18,4,4.7,AF

In [ ]:
drinks.columns

Index(['country', 'beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent'],
      dtype='object')

In [ ]:
# Which continent drinks more beer on average?

# Group the data by continent and calculate the average beer servings
average_beer_servings = drinks.groupby('continent')['beer_servings'].mean()

# Find the continent with the highest average beer servings
continent_with_most_beer = average_beer_servings.idxmax()
highest_average_beer = average_beer_servings.max()

print(f"The continent that drinks the most beer on average is {continent_with_most_beer} with an average of {highest_average_beer} beer servings.")

The continent that drinks the most beer on average is EU with an average of 193.77777777777777 beer servings.

In [ ]:
# For each continent print the statistics for wine consumption.

# Group by continent and get statistics for wine_servings
wine_statistics = drinks.groupby('continent')['wine_servings'].describe()

# Print the statistics for each continent
print(wine_statistics)

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

In [ ]:
# Print the mean alcohol consumption per continent for every column


# Group by continent and calculate the mean for every relevant column
mean_alcohol_consumption = drinks.groupby('continent')[['beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol']].mean()

# Print the mean consumption per continent for each column
print(mean_alcohol_consumption)

           beer_servings  spirit_servings  wine_servings  \
continent
AF             61.471698        16.339623      16.264151
AS             37.045455        60.840909       9.068182
EU            193.777778       132.555556     142.222222
OC             89.687500        58.437500      35.625000
SA            175.083333       114.750000      62.416667

           total_litres_of_pure_alcohol
continent
AF                             3.007547
AS                             2.170455
EU                             8.617778
OC                             3.381250
SA                             6.308333

In [ ]:
# Print the median alcohol consumption per continent for every column

# Group by continent and calculate the median for every relevant column
median_alcohol_consumption = drinks.groupby('continent')[['beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol']].median()

# Print the median consumption per continent for each column
print(median_alcohol_consumption)

           beer_servings  spirit_servings  wine_servings  \
continent
AF                  32.0              3.0            2.0
AS                  17.5             16.0            1.0
EU                 219.0            122.0          128.0
OC                  52.5             37.0            8.5
SA                 162.5            108.5           12.0

           total_litres_of_pure_alcohol
continent
AF                                 2.30
AS                                 1.20
EU                                10.00
OC                                 1.75
SA                                 6.85

In [ ]:
# Print the mean, min and max values for spirit consumption. This time output a DataFrame


# Group by continent and calculate the mean, min, and max for spirit_servings
spirit_consumption_stats = drinks.groupby('continent')['spirit_servings'].agg(['mean', 'min', 'max'])

# Print the resulting DataFrame
print(spirit_consumption_stats)

                 mean  min  max
continent
AF          16.339623    0  152
AS          60.840909    0  326
EU         132.555556    0  373
OC          58.437500    0  254
SA         114.750000   25  302

- 03_Grouping/Occupation/Exercise

In [ ]:
# import necessary libraries
import numpy as np
import pandas as pd

In [ ]:
# Step 2. Import the dataset
# Step 3. Assign it to a variable called users.
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user'
users = pd.read_csv(url, sep='|')
users

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [ ]:
# Step 4. Discover what is the mean age per occupation
mean_age_per_occupation = users.groupby('occupation')['age'].mean()
mean_age_per_occupation

occupation
administrator    38.746835
artist           31.392857
doctor           43.571429
educator         42.010526
engineer         36.388060
entertainment    29.222222
executive        38.718750
healthcare       41.562500
homemaker        32.571429
lawyer           36.750000
librarian        40.000000
marketing        37.615385
none             26.555556
other            34.523810
programmer       33.121212
retired          63.071429
salesman         35.666667
scientist        35.548387
student          22.081633
technician       33.148148
writer           36.311111
Name: age, dtype: float64

In [ ]:
# Step 5. Discover the Male ratio per occupation and sort it from the most to the least
male_ratio_per_occupation = users[users['gender'] == 'M'].groupby('occupation')['gender'].count() / users.groupby('occupation')['gender'].count() * 100
male_ratio_sorted = male_ratio_per_occupation.sort_values(ascending=False)
male_ratio_sorted

occupation
doctor           100.000000
engineer          97.014925
technician        96.296296
retired           92.857143
programmer        90.909091
executive         90.625000
scientist         90.322581
entertainment     88.888889
lawyer            83.333333
salesman          75.000000
educator          72.631579
student           69.387755
other             65.714286
marketing         61.538462
writer            57.777778
none              55.555556
administrator     54.430380
artist            53.571429
librarian         43.137255
healthcare        31.250000
homemaker         14.285714
Name: gender, dtype: float64

In [ ]:
# Step 6. For each occupation, calculate the minimum and maximum ages
min_max_age_per_occupation = users.groupby('occupation')['age'].agg(['min', 'max'])
min_max_age_per_occupation

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

In [ ]:
# Step 7. For each combination of occupation and gender, calculate the mean age
mean_age_per_occupation_gender = users.groupby(['occupation', 'gender'])['age'].mean()
mean_age_per_occupation_gender

occupation     gender
administrator  F         40.638889
               M         37.162791
artist         F         30.307692
               M         32.333333
doctor         M         43.571429
educator       F         39.115385
               M         43.101449
engineer       F         29.500000
               M         36.600000
entertainment  F         31.000000
               M         29.000000
executive      F         44.000000
               M         38.172414
healthcare     F         39.818182
               M         45.400000
homemaker      F         34.166667
               M         23.000000
lawyer         F         39.500000
               M         36.200000
librarian      F         40.000000
               M         40.000000
marketing      F         37.200000
               M         37.875000
none           F         36.500000
               M         18.600000
other          F         35.472222
               M         34.028986
programmer     F         32.166667
               M         33.216667
retired        F         70.000000
               M         62.538462
salesman       F         27.000000
               M         38.555556
scientist      F         28.333333
               M         36.321429
student        F         20.750000
               M         22.669118
technician     F         38.000000
               M         32.961538
writer         F         37.631579
               M         35.346154
Name: age, dtype: float64

In [ ]:
# Step 8. For each occupation present the percentage of women and men
gender_percentage_per_occupation = users.groupby('occupation')['gender'].value_counts(normalize=True) * 100
gender_percentage_per_occupation

occupation     gender
administrator  M          54.430380
               F          45.569620
artist         M          53.571429
               F          46.428571
doctor         M         100.000000
educator       M          72.631579
               F          27.368421
engineer       M          97.014925
               F           2.985075
entertainment  M          88.888889
               F          11.111111
executive      M          90.625000
               F           9.375000
healthcare     F          68.750000
               M          31.250000
homemaker      F          85.714286
               M          14.285714
lawyer         M          83.333333
               F          16.666667
librarian      F          56.862745
               M          43.137255
marketing      M          61.538462
               F          38.461538
none           M          55.555556
               F          44.444444
other          M          65.714286
               F          34.285714
programmer     M          90.909091
               F           9.090909
retired        M          92.857143
               F           7.142857
salesman       M          75.000000
               F          25.000000
scientist      M          90.322581
               F           9.677419
student        M          69.387755
               F          30.612245
technician     M          96.296296
               F           3.703704
writer         M          57.777778
               F          42.222222
Name: proportion, dtype: float64

- 03_Grouping/Regiment/Exercises

In [ ]:
# import necessary libraries
import numpy as np
import pandas as pd

In [ ]:
# Step 2. Create the DataFrame with the following values:

raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'],
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

In [ ]:
# Step 3. Assign it to a variable called regiment. Don't forget to name each column
regiment = pd.DataFrame(raw_data)
regiment

      regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

In [ ]:
# Step 4. What is the mean preTestScore from the regiment Nighthawks?
nighthawks_mean_preTestScore = regiment[regiment['regiment'] == 'Nighthawks']['preTestScore'].mean()
print(f"Mean pre-test score from Nighthawks regiment : {nighthawks_mean_preTestScore}")

Mean pre-test score from Nighthawks regiment : 15.25

In [ ]:
# Step 5. Present general statistics by company
general_stats_by_company = regiment.groupby('company').describe()
general_stats_by_company

        preTestScore                                                      \
               count       mean        std  min   25%   50%    75%   max
company
1st              6.0   6.666667   8.524475  2.0  3.00   3.5   4.00  24.0
2nd              6.0  15.500000  14.652645  2.0  2.25  13.5  29.25  31.0

        postTestScore
                count       mean        std   min    25%   50%   75%   max
company
1st               6.0  57.666667  27.485754  25.0  34.25  66.0  70.0  94.0
2nd               6.0  67.000000  14.057027  57.0  58.25  62.0  68.0  94.0

In [ ]:
# Step 6. What is the mean of each company's preTestScore?
mean_preTestScore_by_company = regiment.groupby('company')['preTestScore'].mean()
mean_preTestScore_by_company

company
1st     6.666667
2nd    15.500000
Name: preTestScore, dtype: float64

In [ ]:
# Step 7. Present the mean preTestScores grouped by regiment and company
mean_preTestScore_by_regiment_company = regiment.groupby(['regiment', 'company'])['preTestScore'].mean()
mean_preTestScore_by_regiment_company

regiment    company
Dragoons    1st         3.5
            2nd        27.5
Nighthawks  1st        14.0
            2nd        16.5
Scouts      1st         2.5
            2nd         2.5
Name: preTestScore, dtype: float64

In [ ]:
# Step 8. Present the mean preTestScores grouped by regiment and company without heirarchical indexing
mean_preTestScore_by_regiment_company_unstacked = regiment.groupby(['regiment', 'company'])['preTestScore'].mean().unstack()
mean_preTestScore_by_regiment_company_unstacked

company      1st   2nd
regiment
Dragoons     3.5  27.5
Nighthawks  14.0  16.5
Scouts       2.5   2.5

In [ ]:
# Step 9. Group the entire dataframe by regiment and company
grouped_regiment_company = regiment.groupby(['regiment', 'company'])
grouped_regiment_company

In [ ]:
# Step 10. What is the number of observations in each regiment and company
num_observations_regiment_company = grouped_regiment_company.size()
num_observations_regiment_company

regiment    company
Dragoons    1st        2
            2nd        2
Nighthawks  1st        2
            2nd        2
Scouts      1st        2
            2nd        2
dtype: int64

In [ ]:
# Step 11. Iterate over a group and print the name and the whole data from the regiment
for name, group in regiment.groupby('regiment'):
    print(f"Regiment Name: {name}")
    print(group)

Regiment Name: Dragoons
   regiment company    name  preTestScore  postTestScore
4  Dragoons     1st   Cooze             3             70
5  Dragoons     1st   Jacon             4             25
6  Dragoons     2nd  Ryaner            24             94
7  Dragoons     2nd    Sone            31             57
Regiment Name: Nighthawks
     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
2  Nighthawks     2nd       Ali            31             57
3  Nighthawks     2nd    Milner             2             62
Regiment Name: Scouts
   regiment company   name  preTestScore  postTestScore
8    Scouts     1st  Sloan             2             62
9    Scouts     1st  Piger             3             70
10   Scouts     2nd  Riani             2             62
11   Scouts     2nd    Ali             3             70